version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: DEBUG
loggers:
  uvicorn:
    handlers: [console]
    level: INFO
    propagate: no
  uvicorn.error:
    handlers: [console]
    level: INFO
    propagate: no
  uvicorn.access:
    handlers: [console]
    level: INFO
    propagate: no
